### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by guizello** [abhishekkr/ansible-dashr#2]
Hello, your project seems to be very interesting.

Unfortunately i should have forgotten something because i only got a "404 page not found" while browsing 127.0.0.1:8001 ..

> go version
> go version go1.4.2 darwin/amd64
> go run dashr.go -http="8888"
> 2015/06/17 17:27:58 Ansible Dashr @ 127.0.0.1:8001

I use MacOS 10.10.

Maybe you could help me ?

Thanks,
Guillaume

**Comment by abhishekkr** [comment]
@guizello currently the view unflods at "127.0.0.1:8001/www-data"
I'll add a redirect at "127.0.0.1:8001/" for it.

This path structure is to have root separation for static-web-data, config-data and ansible-data for dashr.

Let know if this fixes the issue for you.

**Comment by guizello** [comment]
oh shame on me .. thanks it works very well.
Yes i think that a redirect would be good for bad people like me :)
