### ISSUE TITLE
404 Page not found when launching dashr

### ISSUE THREAD

**Issue by hanynowsky** [abhishekkr/ansible-dashr#4]
- Installed golang in a CentOS 6
- created and exported dashr log directory
- Launched

```
go run dashr.go -ansible="/etc/ansible" -fqdn=0.0.0.0
2015/06/30 12:44:12 Ansible Dashr @ 0.0.0.0:8001
```
- No error reported on console; but when I try to open Dashr using web browser I get the following error on a blank page:

```
404 Page not found
```
- Something I missed?

**Comment by abhishekkr** [comment]
@hanynowsky by design the dashr serves at '/www-data', I should have added a redirect as soon @guizello reported it as issue(https://github.com/abhishekkr/ansible-dashr/issues/2).

I've added it there now. The "/" calls shall work now as well.
Please confirm if it work (or not) for you.

**Comment by hanynowsky** [comment]
Yes. I can access the dashboard now. Thanks for your prompt responsiveness.
